name: card_link_pro
description: >
  CardLink Pro — a local-first, fully editable profile card with image/PDF/text/QR/NFC sharing.
version: 1.1.0+2
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core & storage
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  android_intent_plus: ^5.0.2


  # UI & media
  google_fonts: ^6.3.0
  flutter_svg: ^2.0.10
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2
  screenshot: ^3.0.0

  # Links, share, contacts
  url_launcher: ^6.3.2
  share_plus: ^11.1.0
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.1

  # PDF & printing
  pdf: ^3.11.3
  printing: ^5.14.2

  # QR
  qr_flutter: ^4.1.0
  barcode: ^2.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Use flutter_lints instead of the generic lints package to avoid version conflicts
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    # Avatars (3)
    - assets/images/avatars/alkhadi.png
    - assets/images/avatars/mariatou.png
    - assets/images/avatars/avatar_business.png
    # Backgrounds (7)
    - assets/images/backgrounds/amz.jpg
    - assets/images/backgrounds/abstract_wave.jpg
    - assets/images/backgrounds/gradient_sky.jpg
    - assets/images/backgrounds/gradient_sand.jpg
    - assets/images/backgrounds/pattern_dots.jpg
    - assets/images/backgrounds/texture_paper.jpg
    - assets/images/backgrounds/city_soft.jpg
