# title=pubspec.yaml
name: card_link_pro
description: >
  CardLink Pro — a local-first, fully editable profile card with image/PDF/text/QR/NFC sharing.
version: 1.1.0+2
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core & storage
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # UI & media
  google_fonts: ^6.3.0
  flutter_svg: ^2.0.10
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.1.2
  screenshot: ^3.0.0

  # Links, share, contacts
  url_launcher: ^6.3.2
  share_plus: ^11.1.0
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.1

  # PDF & printing
  pdf: ^3.11.3
  printing: ^5.14.2

  # QR
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/alkhadi.png
    - assets/images/mariatou.png
    - assets/images/amz.jpg
